// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/CardWith4ComponentsIsland.tsx";
import * as $$1 from "./islands/Carousel.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/Description.tsx";
import * as $$4 from "./islands/Menu.tsx";
import * as $$5 from "./islands/Modal.tsx";
import * as $$6 from "./islands/ModalContainer.tsx";
import * as $$7 from "./islands/NavMenu.tsx";
import * as $$8 from "./islands/NavMenu2.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/CardWith4ComponentsIsland.tsx": $$0,
    "./islands/Carousel.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/Description.tsx": $$3,
    "./islands/Menu.tsx": $$4,
    "./islands/Modal.tsx": $$5,
    "./islands/ModalContainer.tsx": $$6,
    "./islands/NavMenu.tsx": $$7,
    "./islands/NavMenu2.tsx": $$8,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
